export interface ExamPattern {
  name: string;
  regex: RegExp;
}

export const EXAM_PATTERNS: ExamPattern[] = [
  { name: "Hemograma Completo", regex: /(?:Hemograma\s*Completo|HC)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Hemácias", regex: /(?:Hem[áa]cias|RBC)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Hemoglobina", regex: /(?:Hemoglobina|HGB)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Hematócrito", regex: /(?:Hemat[óo]crito|HCT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Volume Corpuscular Médio", regex: /(?:Volume\s*Corpuscular\s*M[eé]dio|VCM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Hemoglobina Corpuscular Média", regex: /(?:Hemoglobina\s*Corpuscular\s*M[eé]dia|HCM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Concentração de Hemoglobina Corpuscular Média", regex: /(?:Concentra[çc][aã]o\s*de\s*Hemoglobina\s*Corpuscular\s*M[eé]dia|CHCM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Índice de Distribuição de Eritrócitos", regex: /(?:[ÍI]ndice\s*de\s*Distribui[çc][aã]o\s*de\s*Eritr[óo]citos|RDW)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Leucócitos", regex: /(?:Leuc[óo]citos|WBC)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Neutrófilos", regex: /(?:Neutr[óo]filos|NEUT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Linfócitos", regex: /(?:Linf[óo]citos|LINFO)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Monócitos", regex: /(?:Mon[óo]citos|MONO)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Eosinófilos", regex: /(?:Eosin[óo]filos|EOS)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Basófilos", regex: /(?:Bas[óo]filos|BASO)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Plaquetas", regex: /(?:Plaquetas|PLT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Volume Médio Plaquetário", regex: /(?:Volume\s*M[eé]dio\s*Plaquet[áa]rio|VMP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Glicemia de Jejum", regex: /(?:Glicemia\s*de\s*Jejum|GJ)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Hemoglobina Glicada", regex: /(?:Hemoglobina\s*Glicada|HbA1c)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Frutosamina", regex: /(?:Frutosamina|FRUCT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Insulina", regex: /(?:Insulina|INS)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Peptídeo C", regex: /(?:Pept[íi]deo\s*C|PC)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Teste de Tolerância à Glicose", regex: /(?:Teste\s*de\s*Toler[âa]ncia\s*[àa]\s*Glicose|TOTG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Colesterol Total", regex: /(?:Colesterol\s*Total|CT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Colesterol HDL", regex: /(?:Colesterol\s*HDL|HDL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Colesterol LDL", regex: /(?:Colesterol\s*LDL|LDL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Colesterol VLDL", regex: /(?:Colesterol\s*VLDL|VLDL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Triglicerídeos", regex: /(?:Triglicer[íi]deos|TG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Apolipoproteína A1", regex: /(?:Apolipoprote[íi]na\s*A1|APOA1)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Apolipoproteína B", regex: /(?:Apolipoprote[íi]na\s*B|APOB)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Ureia", regex: /(?:Ureia|UR)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Creatinina", regex: /(?:Creatinina|CR)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Clearance de Creatinina", regex: /(?:Clearance\s*de\s*Creatinina|CLCR)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Ácido Úrico", regex: /(?:[ÁA]cido\s*[ÚU]rico|AU)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Sódio", regex: /(?:S[óo]dio|Na)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Potássio", regex: /(?:Pot[áa]ssio|K)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cloro", regex: /(?:Cloro|Cl)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cálcio Total", regex: /(?:C[áa]lcio\s*Total|CaT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cálcio Ionizado", regex: /(?:C[áa]lcio\s*Ionizado|CaI)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Fósforo", regex: /(?:F[óo]sforo|P)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Magnésio", regex: /(?:Magn[ée]sio|Mg)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "TGO (AST)", regex: /(?:TGO|AST)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "TGP (ALT)", regex: /(?:TGP|ALT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Gama-GT", regex: /(?:Gama-?GT|GGT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Fosfatase Alcalina", regex: /(?:Fosfatase\s*Alcalina|FA)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Bilirrubina Total", regex: /(?:Bilirrubina\s*Total|BT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Bilirrubina Direta", regex: /(?:Bilirrubina\s*Direta|BD)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Bilirrubina Indireta", regex: /(?:Bilirrubina\s*Indireta|BI)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Albumina", regex: /(?:Albumina|ALB)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Proteínas Totais", regex: /(?:Prote[ií]nas\s*Totais|PT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "TSH (Hormônio Tireoestimulante)", regex: /(?:TSH)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "T4 Livre", regex: /(?:T4\s*Livre|T4L)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "T3 Livre", regex: /(?:T3\s*Livre|T3L)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "T3 Total", regex: /(?:T3\s*Total|T3T)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Anti-TPO (Anticorpos Antitireoperoxidase)", regex: /(?:Anti-?TPO|ATPO)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Anti-Tireoglobulina", regex: /(?:Anti-?Tireoglobulina|ATG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Testosterona Total", regex: /(?:Testosterona\s*Total|TT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Testosterona Livre", regex: /(?:Testosterona\s*Livre|TL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Progesterona", regex: /(?:Progesterona|PROG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Estradiol", regex: /(?:Estradiol|E2)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "FSH (Hormônio Folículo Estimulante)", regex: /(?:FSH)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "LH (Hormônio Luteinizante)", regex: /(?:LH)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cortisol", regex: /(?:Cortisol|CORT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Prolactina", regex: /(?:Prolactina|PRL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "SHBG (Globulina Ligadora de Hormônios Sexuais)", regex: /(?:SHBG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Proteína C Reativa", regex: /(?:Prote[ií]na\s*C\s*Reativa|PCR)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Velocidade de Hemossedimentação", regex: /(?:Velocidade\s*de\s*Hemossedimenta[çc][aã]o|VHS)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Fator Reumatoide", regex: /(?:Fator\s*Reumatoide|FR)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "FAN (Fator Antinúcleo)", regex: /(?:FAN|Fator\s*Antin[úu]cleo)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Complemento C3", regex: /(?:Complemento\s*C3|C3)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Complemento C4", regex: /(?:Complemento\s*C4|C4)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Ferro Sérico", regex: /(?:Ferro\s*S[eé]rico|Fe)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Ferritina", regex: /(?:Ferritina|FER)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Transferrina", regex: /(?:Transferrina|TRF)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Capacidade Total de Ligação do Ferro", regex: /(?:Capacidade\s*Total\s*de\s*Liga[çc][aã]o\s*do\s*Ferro|CTLF)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Vitamina B12", regex: /(?:Vitamina\s*B12|VitB12)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Ácido Fólico", regex: /(?:[ÁA]cido\s*F[óo]lico|AF)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Vitamina D (25-OH)", regex: /(?:Vitamina\s*D|25-?OH|VitD)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "CK (Creatina Kinase)", regex: /(?:CK|Creatina\s*Kinase)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "CK-MB", regex: /(?:CK-?MB)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Troponina I", regex: /(?:Troponina\s*I|TROP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "BNP (Peptídeo Natriurético Cerebral)", regex: /(?:BNP|Pept[íi]deo\s*Natriur[ée]tico\s*Cerebral)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Dímero-D", regex: /(?:D[íi]mero-?D|DD)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Tempo de Protrombina", regex: /(?:Tempo\s*de\s*Protrombina|TP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "INR (Relação Normalizada Internacional)", regex: /(?:INR)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Tempo de Tromboplastina Parcial Ativada", regex: /(?:TTPA)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "PSA Total", regex: /(?:PSA\s*Total|PSA)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "PSA Livre", regex: /(?:PSA\s*Livre|PSAL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "CEA (Antígeno Carcinoembrionário)", regex: /(?:CEA)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "CA 125", regex: /(?:CA\s*125|CA125)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "CA 15-3", regex: /(?:CA\s*15-3|CA153)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "CA 19-9", regex: /(?:CA\s*19-9|CA199)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Alfafetoproteína", regex: /(?:Alfafetoprote[íi]na|AFP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Beta-HCG Quantitativo", regex: /(?:Beta-?HCG|BHCG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "HIV 1 e 2", regex: /(?:HIV)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "HBsAg (Antígeno de Superfície do HBV)", regex: /(?:HBsAg|HBSAG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Anti-HBs (Anticorpo de Superfície do HBV)", regex: /(?:Anti-?HBs|AHBS)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Anti-HCV (Anticorpo para Hepatite C)", regex: /(?:Anti-?HCV|AHCV)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "VDRL (Sífilis)", regex: /(?:VDRL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Toxoplasmose IgG", regex: /(?:Toxoplasmose\s*IgG|TOXOG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Toxoplasmose IgM", regex: /(?:Toxoplasmose\s*IgM|TOXOM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Dengue NS1", regex: /(?:Dengue\s*NS1|DENNS1)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Análise de Urina (EAS)", regex: /(?:An[áa]lise\s*de\s*Urina|EAS)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Urocultura", regex: /(?:Urocultura|UC)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Exame Parasitológico de Fezes", regex: /(?:Exame\s*Parasitol[óo]gico\s*de\s*Fezes|EPF)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Pesquisa de Sangue Oculto nas Fezes", regex: /(?:Pesquisa\s*de\s*Sangue\s*Oculto\s*nas\s*Fezes|SOF)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Álcool Desidrogenase", regex: /(?:[ÁA]lcool\s*Desidrogenase|ADH)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Lactato Desidrogenase", regex: /(?:Lactato\s*Desidrogenase|LDH)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Amilase", regex: /(?:Amilase|AMI)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Lipase", regex: /(?:Lipase|LIP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Homocisteína", regex: /(?:Homociste[íi]na|HCY)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cultura de Urina", regex: /(?:Cultura\s*de\s*Urina|UCUL)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Hormônio Paratireoidiano", regex: /(?:Horm[ôo]nio\s*Paratireoidiano|PTH)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cálcio Urinário", regex: /(?:C[áa]lcio\s*Urin[áa]rio|CaU)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "24 Horas", regex: /(?:24\s*Horas|24H)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Relação Albumina/Globulina (A/G)", regex: /(?:Rela[çc][aã]o\s*Albumina\/Globulina|A\/G|AG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Fosfatase Ácida", regex: /(?:Fosfatase\s*[ÁA]cida|FAcid)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cistatina C", regex: /(?:Cistatina\s*C|CISTC)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Osmolalidade Urinária", regex: /(?:Osmolalidade\s*Urin[áa]ria|OSMU)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Sódio Urinário", regex: /(?:S[óo]dio\s*Urin[áa]rio|NaU)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Potássio Urinário", regex: /(?:Pot[áa]ssio\s*Urin[áa]rio|KU)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Reticulócitos", regex: /(?:Reticul[óo]citos|RET)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Tempo de Trombina", regex: /(?:Tempo\s*de\s*Trombina|TT)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Fibrinogênio", regex: /(?:Fibrinog[êe]nio|FIB)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "ACTH (Hormônio Adrenocorticotrófico)", regex: /(?:ACTH)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "DHEA-S (Sulfato de Dehidroepiandrosterona)", regex: /(?:DHEA-?S|DHEAS)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "17-OH-Progesterona", regex: /(?:17-?OH-?Progesterona|17OHP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Insulina Pós-Prandial", regex: /(?:Insulina\s*P[óo]s-?Prandial|INSPP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Zinco", regex: /(?:Zinco|Zn)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Cobre", regex: /(?:Cobre|Cu)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Vitamina A", regex: /(?:Vitamina\s*A|VitA)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Vitamina E", regex: /(?:Vitamina\s*E|VitE)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "PCR Ultra-Sensível (HS-CRP)", regex: /(?:PCR\s*Ultra-?Sens[íi]vel|HS-?CRP)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Mioglobina", regex: /(?:Mioglobina|MIO)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Citomegalovírus IgG", regex: /(?:Citomegalov[íi]rus\s*IgG|CMV\s*IgG|CMVIGG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Citomegalovírus IgM", regex: /(?:Citomegalov[íi]rus\s*IgM|CMV\s*IgM|CMVIGM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Rubéola IgG", regex: /(?:Rub[ée]ola\s*IgG|RUBIGG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Rubéola IgM", regex: /(?:Rub[ée]ola\s*IgM|RUBIGM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Hepatite A IgM", regex: /(?:Hepatite\s*A\s*IgM|HAV\s*IgM|HAVIGM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Zika Vírus IgM", regex: /(?:Zika\s*V[íi]rus\s*IgM|ZIKAIGM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Chikungunya IgM", regex: /(?:Chikungunya\s*IgM|CHIKIGM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Beta-HCG Qualitativo", regex: /(?:Beta-?HCG\s*Qualitativo|BHCGQ)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Estriol", regex: /(?:Estriol|E3)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Anticardiolipina IgG", regex: /(?:Anticardiolipina\s*IgG|ACARDIGG)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Anticardiolipina IgM", regex: /(?:Anticardiolipina\s*IgM|ACARDIGM)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
  { name: "Anticorpo Anti-β2 Glicoproteína 1", regex: /(?:Anti-?β2\s*Glicoprote[ií]na\s*1|B2GP1)[\s:]*([\d.,]+)\s*(\w+\/?\w*)?/i },
];
